package com.ritallus.logsmvvm.backend.core.service;

import java.time.LocalDateTime;
import java.util.UUID;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.atomic.AtomicInteger;

import com.ritallus.logsmvvm.backend.core.model.LogLine;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

@Slf4j
@Service
public class LogStreamService {

    // Devuelve la cola para que el hilo de la UI la pueda escuchar
    // El buffer en memoria compartido
    @Getter
    private final BlockingQueue<LogLine> logBuffer = new LinkedBlockingQueue<>(5000);
    private final ExecutorService backendExecutor;
    // Mantiene la referencia de la tarea corriendo para poder cancelarla selectivamente
    private Future<?> streamingTask;
    @Getter
    private volatile boolean isRunning = false;

    public LogStreamService(@Qualifier("backendLogExecutor") ExecutorService backendExecutor) {
        this.backendExecutor = backendExecutor;
    }

    public synchronized void startStreaming() {
        if (isRunning) return;
        isRunning = true;
        log.info("Iniciando hilo productor de logs");

        // Enviamos la tarea al pool administrado por Spring y guardamos el token de control (Future)
        streamingTask = backendExecutor.submit(() -> {
            log.info("Hilo productor iniciado");
            AtomicInteger counter = new AtomicInteger(100);
            String[] levels = {"INFO", "WARN", "ERROR", "DEBUG"};

            try {
                // Evaluamos tanto el flag de control como el estado de interrupción del hilo
                while (isRunning && !Thread.currentThread().isInterrupted()) {
                    int currentId = counter.incrementAndGet();
                    String level = levels[(int) (Math.random() * levels.length)];

                    LogLine log = new LogLine(
                            UUID.randomUUID().toString(),
                            LocalDateTime.now(),
                            level,
                            Thread.currentThread().getName(), // Verás el prefijo del Virtual Thread en UI
                            "c.r.l.b.c.s.LogStreamService",
                            "MSG-" + currentId,
                            "Streaming data transaction payload simulated " + currentId
                                    +
                                    "AQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQQQQQQQQQQQQQQQQQQQAQQQ"
                    );

                    logBuffer.put(log);

                    Thread.sleep(100);
                }
            } catch (InterruptedException e) {
                // Al capturar InterruptedException, se limpia el flag de interrupción, lo volvemos a encender
                Thread.currentThread().interrupt();
            } finally {
                log.info("Streaming finalizado limpiamente en el backend.");
            }
        });
    }

    public synchronized void stopStreaming() {
        if (!isRunning) return;
        isRunning = false;

        if (streamingTask != null) {
            // El true fuerza el envío de la señal de interrupción al hilo sin matar al ExecutorService completo
            streamingTask.cancel(true);
        }
    }

}
