spring.aop.proxy-target-class=false
# Nombre del archivo. Se creará automáticamente en la raíz de tu proyecto
spring.datasource.url=jdbc:sqlite:kabrilla_logs.db
spring.datasource.driver-class-name=org.sqlite.JDBC
# Configuración del pool de conexiones (Hikari) con los PRAGMAs para el streaming masivo
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.connection-init-sql=PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA cache_size=-2000;